name: Testing

## retry2
on:
  push:
    branches:
      - 'main'
permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cachev4
        with:
          path: |
            ~/.cache/ms-playwright
            **/node_modules/playwright
          key: cache-playwrightv4

      - name: Check Pre directories
        run: ls

      - name: Install playwright deps
        if: steps.playwright-cachev4.outputs.cache-hit != 'true'
        run: |
        yarn
        yarn playwright install-deps

      - name: Check POST directories
        run: |
          ls

      # - name: Debug
      #   if: ${{ always() }}
      #   uses: mxschmitt/action-tmate@v3


      # - name: Check NPM
      #   run: npm ls --depth=1
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
