name: Testing

## retry2
on:
  push:
    branches:
      - 'main'
permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          # cache: yarn



      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache_v5
        with:
          path: |
            ~/.cache/ms-playwright
            **/node_modules/playwright
          key: cache-playwright_v5

      - name: Install playwright deps
        if: steps.playwright-cache_v5.outputs.cache-hit != 'true'
        run: yarn
        
        
        
      - run: |
        rm package.json yarn.lock
        yarn init -y
        yarn add playwright @playwright/test -D -W
        yarn playwright install-deps

      - name: Debug
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3

      # - name: Cache playwright binaries
      #   uses: actions/cache@v3
      #   id: playwright-cache_v3
      #   with:
      #     path: |
      #       ~/.cache/ms-playwright
      #       **/node_modules/playwright
      #     key: cache-playwright_v3

      # - name: Check Pre directories
      #   run: ls

      # - name: Install playwright deps
      #   if: steps.playwright-cache_v3.outputs.cache-hit != 'true'
      #   run: yarn add playwright -D -W && yarn playwright install-deps

      # - name: Check POST directories
      #   run: |
      #     yarn

      # - name: Debug
      #   if: ${{ always() }}
      #   uses: mxschmitt/action-tmate@v3


      # - name: Check NPM
      #   run: npm ls --depth=1
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
