name: Testing

on:
  push:
    branches:
      - 'main'
permissions:
  contents: read

jobs:
  test-ga:
    name: Testing
    runs-on: ubuntu-20.04
    environment: production

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: |
          npx playwright install-deps
          npx playwright install
